Repository BHoM/Test_Toolkit, pull requests merged in 2019-11, with the labels that each got.

#47 Fix call to incorrect method in IGetDeclaringClass
  Test_Engine/Query/GetDelaringClass.cs
Labels: type:bug

#57 Update yml files
  .ci/check-all-depandants.yml
  .ci/check-core.yml
  .ci/run-compliance-tests.yml
Labels: severity:low

#69 Update Dependant CI Checks to merge with master
  CloneAndBuildCore.ps1
  CloneAndBuildDependants.ps1
  CloneAndBuildDependencies.ps1
Labels: severity:critical

#79 Resolve compiler warnings
  Test_Test/AdapterTests/InputParameterStartsLower.cs
Labels: type:compliance

#90 Add unit tests for checking project files
  Test_Test/AdapterTests/CheckProjectFile.cs
  Test_Test/AdapterTests/ContainsCopyright.cs
  Test_Test/EngineTests/CheckProjectFile.cs
  Test_Test/Test_Test.csproj
  Test_Test/oMTests/CheckProjectFile.cs
Labels: type:compliance
