Repository BHoM/Test_Toolkit, pull requests merged in 2020-11, with the labels that each got.

#289 Re-serialising all test sets
  Datasets/TestSets/Structure/Bar/01 - Straight planar bars.json
  Datasets/TestSets/Structure/Bar/02 - Straight Vertical bars.json
  Datasets/TestSets/Structure/Bar/03 - Straight rotating planar bars.json
  Datasets/TestSets/Structure/Bar/04 - Straight rotating vertical bars.json
  Datasets/TestSets/Structure/Bar/05 - Random Orientated bars.json
  Datasets/TestSets/Structure/Bar/06 - Random Orientated rotating bars.json
  Datasets/TestSets/Structure/Bar/07 - Small Frame.json
  Datasets/TestSets/Structure/Bar/08 - FreeForm Frame.json
  Datasets/TestSets/Structure/Bar/09 - Bars with releases.json
  Datasets/TestSets/Structure/BarRelease/01 - Bar Releases.json
  Datasets/TestSets/Structure/Constraint6DOF/01 - fix or free.json
  Datasets/TestSets/Structure/Constraint6DOF/02 - fix or spring.json
  Datasets/TestSets/Structure/FEMesh/01 - Property Test - Concrete - Constant Thickness.json
  Datasets/TestSets/Structure/FEMesh/02 - Property Test - Concrete - Ribbed.json
  Datasets/TestSets/Structure/FEMesh/03 - Property Test - Concrete - Waffle.json
  Datasets/TestSets/Structure/FEMesh/04 - Property Test - Concrete - LoadingPanelProperty.json
  Datasets/TestSets/Structure/FEMesh/05 - Property Test - Steel - ConstantThickness.json
  Datasets/TestSets/Structure/FEMesh/06 - Node Test - Three Node Planar FEMesh.json
  Datasets/TestSets/Structure/FEMesh/07 - Node Test - Four Node Planar FEMesh.json
  Datasets/TestSets/Structure/FEMesh/08 - Planarity Test - Single Curvature FEMesh.json
  Datasets/TestSets/Structure/FEMesh/09 - Planarity Test - Double Curvature FEMesh.json
  Datasets/TestSets/Structure/IMaterialFragment/01 - Object Test - Steel.json
  Datasets/TestSets/Structure/IMaterialFragment/02 - Object Test - Concrete.json
  Datasets/TestSets/Structure/IMaterialFragment/03 - Object Test - Aluminium.json
  Datasets/TestSets/Structure/IMaterialFragment/04 - Object Test - Timber.json
  Datasets/TestSets/Structure/IMaterialFragment/05 - Zero Property Test - E.json
  Datasets/TestSets/Structure/IMaterialFragment/06 - Zero Property Test - v.json
  Datasets/TestSets/Structure/IMaterialFragment/07 - Unit Property Test - v.json
  Datasets/TestSets/Structure/IMaterialFragment/08 - Zero Property Test - tC.json
  Datasets/TestSets/Structure/IMaterialFragment/09 - Zero Property Test - Density.json
  Datasets/TestSets/Structure/IMaterialFragment/10 - Zero Property Test - Damping Ratio.json
  Datasets/TestSets/Structure/IMaterialFragment/11 - Unit Property Test - Damping ratio.json
  Datasets/TestSets/Structure/IMaterialFragment/12 - Zero Property Test -  YieldStress.json
  Datasets/TestSets/Structure/IMaterialFragment/13 - Zero Property Test -   UltimateStress.json
  Datasets/TestSets/Structure/IMaterialFragment/14 - Equal Properties Test - YieldStress equals UltimateStress.json
  Datasets/TestSets/Structure/IMaterialFragment/15 - Zero Property Test - CubeStrength.json
  Datasets/TestSets/Structure/IMaterialFragment/16 - Zero Property Test - CylinderStrength.json
  Datasets/TestSets/Structure/IMaterialFragment/17 - Equal Properties Test - Cylinder equals CubeStrength.json
  Datasets/TestSets/Structure/ISectionProperty/01 - Steel Library Sections.json
  Datasets/TestSets/Structure/ISectionProperty/02 - Steel Fabricated Sections.json
  Datasets/TestSets/Structure/ISectionProperty/03 - Steel Freeform Sections.json
  Datasets/TestSets/Structure/ISectionProperty/04 - Concrete Parametric Sections.json
  Datasets/TestSets/Structure/ISectionProperty/05 - Concrete Freeform Sections.json
  Datasets/TestSets/Structure/Node/01 - Constraint6DOF fix or free.json
  Datasets/TestSets/Structure/Node/02 - Constraint6DOF fix or spring.json
  Datasets/TestSets/Structure/Panel/01 - Property Test - Concrete - Slabs.json
  Datasets/TestSets/Structure/Panel/02 - Property Test - Concrete - Walls.json
  Datasets/TestSets/Structure/Panel/03 - Property Test - Steel - Slabs.json
  Datasets/TestSets/Structure/Panel/04 - Property Test - Steel - Walls.json
  Datasets/TestSets/Structure/Panel/05 - Property Test - LoadingPanel - Slabs.json
  Datasets/TestSets/Structure/Panel/06 - Property Test -  LoadingPanel  - Walls.json
  Datasets/TestSets/Structure/Panel/07 - Outline Tests - Slabs.json
  Datasets/TestSets/Structure/Panel/08 - Outline Tests - Walls.json
  Datasets/TestSets/Structure/Panel/09 - Outline Tests - Freeform.json
  Datasets/TestSets/Structure/Panel/10 - Opening Tests - Slabs.json
  Datasets/TestSets/Structure/Panel/11 - Opening Tests - Walls.json
  Datasets/TestSets/Structure/Panel/12 - Opening Tests - FreeForm.json
Labels: type:compliance

#294 Add HasValidPreviousVersionAttribute test
  CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj
  CodeComplianceTest_Engine/Query/Checks/HasValidPreviousVersionAttribute.cs
Labels: type:feature

#296 Update IsValidQuantityInputAttribute.cs
  CodeComplianceTest_Engine/Query/DynamicChecks/IsValidQuantityInputAttribute.cs
Labels: type:external-api-changes

#299 Add input from property allowances and checks
  CodeComplianceTest_Engine/Query/Checks/InputAttributeHasMatchingParameter.cs
  CodeComplianceTest_Engine/Query/Checks/InputAttributeIsUnique.cs
  CodeComplianceTest_Engine/Query/Checks/IsInputAttributePresent.cs
  CodeComplianceTest_Engine/Query/InputAttributes.cs
Labels: type:feature

#305 Fix punctuation check and ValidDataset reporting
  CodeComplianceTest_Engine/Query/Checks/AttributeHasEndingPunctuation.cs
  CodeComplianceTest_Engine/Query/DynamicChecks/IsValidDataset.cs
Labels: type:bug
