Repository BHoM/Test_Toolkit, pull requests merged in 2020-04, with the labels that each got.

#193 InteroperabilityTest_Engine: Align to changes in BH.oM.Diffing.DiffConfig
  InteroperabilityTest_Engine/Query/IsEqual.cs
Labels: type:compliance, type:external-api-changes

#215 Test_Engine: Migrate Dummy and IsEqual methods from Reflection Engine
  Test_Engine/Compute/DummyObject.cs
  Test_Engine/Properties/AssemblyInfo.cs
  Test_Engine/Query/IsEqual.cs
  Test_Engine/Test_Engine.csproj
  Test_Engine/app.config
  Test_Engine/packages.config
  Test_Toolkit.sln
Labels: type:feature

#225 Prevent Virtual keyword checking on interface classes
  Test_oM/ComplianceResult.cs
Labels: type:bug

#227 Add LifeCycleAssesment to core projects
  CodeComplianceTest_Engine/Compute/CheckReferences.cs
Labels: type:bug

#229 Fix adapter core project reference checking
  CodeComplianceTest_Engine/Compute/CheckReferences.cs
Labels: type:bug

#230 Turn on convert method checks for Adapter projects
  CodeComplianceTest_Engine/Query/Checks/IsValidConvertMethodName.cs
Labels: type:feature

#231 Fix erroneous punctuation check for multi output
  CodeComplianceTest_Engine/Query/Checks/AttributeHasEndingPunctuation.cs
Labels: type:bug
