Repository BHoM/Test_Toolkit, pull requests merged in 2020-02, with the labels that each got.

#143 Remove requirement for deprecated methods to have descriptions
  CodeComplianceTest_Engine/Query/Checks/HasDescriptionAttribute.cs
  CodeComplianceTest_Engine/Query/Checks/HasMatchingInputDescription.cs
  CodeComplianceTest_Engine/Query/Checks/HasOutputAttribute.cs
Labels: type:compliance

#144 Allow path to contain return type rather than only filename
  CodeComplianceTest_Engine/Query/Checks/CreateMethodFileNameMatchesReturnType.cs
Labels: type:feature

#148 Update HasMachingInputDescription to account for new quantities attributes
  CodeComplianceTest_Engine/Query/Checks/HasMatchingInputDescription.cs
Labels: severity:critical, type:bug

#152 Fix parameter count of InputAttribute
  CodeComplianceTest_Engine/Query/Checks/HasMatchingInputDescription.cs
  CodeComplianceTest_Engine/Query/Checks/InputAttributeMatchesParameter.cs
Labels: type:bug

#153 Add check that Input Attributes are unique
  CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj
  CodeComplianceTest_Engine/Query/Checks/InputAttributeIsUnique.cs
  CodeComplianceTest_Test/AdapterTests/InputAttributeIsUnique.cs
  CodeComplianceTest_Test/CodeComplianceTest_Test.csproj
  CodeComplianceTest_Test/EngineTests/InputAttributeIsUnique.cs
Labels: type:feature

#156 Add Adapter Create and Read method compliance
  CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj
  CodeComplianceTest_Engine/Query/DynamicChecks/AdapterCreateMethodIsValid.cs
  CodeComplianceTest_Engine/Query/DynamicChecks/AdapterReadMethodIsValid.cs
Labels: type:feature

#158 Allow for Interface convert methods
  CodeComplianceTest_Engine/Query/Checks/IsValidConvertMethodName.cs
Labels: type:bug

#166 Change error message on input parameters
  CodeComplianceTest_Engine/Query/Checks/InputParameterStartsLower.cs
Labels: type:compliance
